### ISSUE TITLE
Multiple JIRA project prefixes

### ISSUE THREAD

**Issue by moreorover** [nemwiz/jira-commit-message-intellij-plugin#51]
It would be very helpful to have an option to setup multiple JIRA project prefixes.

**Comment by nemwiz** [comment]
You need to give me a bit more info on your use case. 

I think you've found a bug, because multiple prefixes should already be supported in a way. The plugin settings should only be applicable per project (as indicated with this icon, see below) but for some reason it doesn't work and it applies it for all projects. I'll have to investigate this.

In other words, this option allows you to configure a different prefix (but only one) for each repo/project. Or do you need multiple prefixes on a single repo/project?
![image](https://user-images.githubusercontent.com/15953555/174234479-8ed33564-a408-4050-a700-e4dc19d0d727.png)

**Comment by moreorover** [comment]
On a single project I might have JIRA issues with different prefixes. I think the easiest solution to this would be if I could separate prefixes with comma.
![image](https://user-images.githubusercontent.com/17711314/174258445-7c894159-1ad6-4783-a1a9-9406bb371b5c.png)

**Comment by nemwiz** [comment]
Okay, all clear now. While I agree that comma separated list would be the easiest choice, it's a bit complicated for validation and maintenance. I might need to change the input field a bit, let's see.

**Comment by nemwiz** [comment]
Hi @moreorover,

I've implemented the changes to support multiple prefixes. Before I release, would you be so kind to test it out? Below is the latest version. You can install it manually by going to Preferences > Plugins > ⚙️ > Install plugin from disk...

Let me know if you encounter any issues.

[jira-commit-message-3.0.0.zip](https://github.com/nemwiz/jira-commit-message-intellij-plugin/files/9024217/jira-commit-message-3.0.0.zip)

**Comment by moreorover** [comment]
Just checked. Can confirm, it works.

**Comment by nemwiz** [comment]
Perfect. Thanks for helping out with testing. I've just released a new version, it usually takes 1-2 days for JetBrains approval before it becomes available. I'm closing this issue. :+1:
