### ISSUE TITLE
Ability to auto-detect prefix from branch names

### ISSUE THREAD

**Issue by stefancrowe** [nemwiz/jira-commit-message-intellij-plugin#53]
Would it be possible to have some auto-detection, perhaps based on a regular expression, for JIRA issue prefixes based on the branch name?

For example - the following regular expression would match the [default format](https://confluence.atlassian.com/adminjiraserver/changing-the-project-key-format-938847081.html#:~:text=By%20default%2C%20Jira%20issue%20keys,the%20project%20key.) e.g. `PROJECT-123-some-random-branch`:

`[A-Z]{2,}-\d+-`

I realise that's a simple example as the format for Jira project keys can have slightly more complex formatting so maybe make the regular expression customisable in the plugin settings?

**Comment by nemwiz** [comment]
Could you give some examples on how your prefixes look like?

From the linked document, I've tried these prefixes:
- `PROJECT_TEST` and branch name `PROJECT_TEST-123`
- `JIRA_TEST-PROJ` and branch name `JIRA_TEST-PROJ-123-random-branch`

Both of them work with the existing implementation, so I'm a bit unclear on what you are asking for? :)
On the topic of regex, you can have a look at [this issue](https://github.com/nemwiz/jira-commit-message-intellij-plugin/pull/4).

**Comment by stefancrowe** [comment]
Apologies I may not have been clear.

My request is if instead of having to specify all the 'Jira project prefixes' manually, we want the plugin to automatically attempt to find prefixes based on the standard format of Jira prefixes - the regex was just an example of how it could do this.

**Comment by nemwiz** [comment]
Very interesting idea! I do see value in this feature, but to be honest as well, how often do you need to specify new Jira prefixes? We don't join new projects every day and adding a prefix is a one time thing.

The effort of adding this feature is very high and the priority is low since it's more of a nice to have feature. I'll add it to the backlog.
If you are keen on implementing this, let me know, I'd be happy to support.

**Comment by nemwiz** [comment]
@stefancrowe It's been a while, but I've managed to implement this. Would you be keen on testing it out? Attached is the latest version.
Support has been added for e.g. `PROJECT-123` or `PROJECT_123`. I haven't added non-standard project keys due to complexity and no one has been asking for this feature yet. As per documentation, the Jira default key is formatted as `PROJECT-123`, so I suspect majority goes with that.
[jira-commit-message-3.2.0.zip](https://github.com/nemwiz/jira-commit-message-intellij-plugin/files/10470130/jira-commit-message-3.2.0.zip)

**Comment by stefancrowe** [comment]
@nemwiz I just tested this and happy to report it worked as expected.

The branch setup used is the default (`PROJECT-123`) and it correctly detected this when I tried various branch combinations (the underscore alternative `PROJECT_123` also worked).

No signs of any bugs/issues.

**Comment by nemwiz** [comment]
Thanks for proposing and testing out this cool feature. 👍 I've released the new version, it should be available in 1-2 days.
If you enjoy this plugin, please support us by [leaving a review or rating](https://plugins.jetbrains.com/plugin/14310-jira-id-commit-message)
