### ISSUE TITLE
Update commit prefix on branch switch in tool window

### ISSUE THREAD

**Issue by thijmenketel** [nemwiz/jira-commit-message-intellij-plugin#56]
When using the tool window for committing the message prefix won't update on a branch switch, it would be very nice if that happens. 

#### Steps to reproduce

1. Use commit tool window instead of commit dialog
2. Open commit tool window
3. Switch branch

The prefix does not update in this case.

**Comment by nemwiz** [comment]
Good suggestion. This feature might not be possible due to the limitation of IntelliJ platform, I'll have to dig into the documentation before confirming this.
The plugin internally listens for certain events that are emitted by IntelliJ, if there is no event emitted when a branch changes then it will be difficult, but let me check.

As a workaround, you can use the generate the commit message button that is exposed by the plugin. It's this frog icon, see screenshot below. When you change the branch, click it and a new message will be generated.

Thanks for pointing this out. I still use the commit dialog exclusively, but I'll improve so that the functionality works for both windows.

![image](https://user-images.githubusercontent.com/15953555/210948319-538c1a28-5a45-448d-9870-ea87ea0d1137.png)

**Comment by nemwiz** [comment]
This feature has been added in v3.1.0
