### ISSUE TITLE
Cast to uppercase.

### ISSUE THREAD

**Issue by REFUZIION** [nemwiz/jira-commit-message-intellij-plugin#70]
We prefer to use lowercase branch names, so the key is still being recognized by the plugin now, however because its lowercase jira does not pick up on it and doesnt link the commit to that ticket.

Solution:
I'd like to see a checkbox that casts the jira key to uppercase.

**Comment by nemwiz** [comment]
According to [Atlassian docs](https://confluence.atlassian.com/adminjiraserver/changing-the-project-key-format-938847081.html) the Jira project key is always uppercased, so I'm thinking of making this a default behavior instead of adding another checkbox. In your example, the plugin would _automatically_ uppercase the key in the commit message.

Just of curiosity - why do you lowercase the project key in your branch names?

**Comment by REFUZIION** [comment]
Within my team we used to use both uppercase and lowercase branches but we all decided that its easier for all of us if we all use the same type, and since there were more people using lowercase than uppercase we stuck to that

**Comment by nemwiz** [comment]
@REFUZIION Which of the plugin options for detecting the project key are you using?
There is an option to let plugin do it automatically and another to specify the key manually. I guess the manual one. Would be good if you can share a screenshot of the plugin settings.

The thing is, I can only add uppercase support for the second option. Everyone has different branch naming, but the automatic option relies on Jira project key to be upper-cased in the branch. This is by Jira convention. Consider the following branch names for a project with key `MARCOM`:

- `MARCOM-381-cool-feature`
- `marcom-381-cool-feature`

For the second scenario the plugin is not able to automatically detect what is the project key between `marcom` `cool` and `feature`. For this to work, the project key needs to be specified inside the plugin settings (this already exists).

So as said, I will add support for the second option and try to extract the project key regardless of the uppercase or lowercase. I would also suggest to re-evaluate your branch naming because it's not following the Jira convention.

Thanks

**Comment by REFUZIION** [comment]
Some example keys id have are: bug/fuze-3002, feat/fuze-3103 currently the module works perfectly the only thing I’d love is a way of casting the jira key to uppercase

**Comment by REFUZIION** [comment]
Hello there, here is the screenshot of my settings as requested:
![Screenshot 2023-08-07 at 16 23 00](https://github.com/nemwiz/jira-commit-message-intellij-plugin/assets/57800730/1fa391b7-fa15-4d02-b0f7-07b5c5cae862)

**Comment by nemwiz** [comment]
Okay, I've added this in the latest version.
Could you test it out?

You can install this version by going to Plugins -> Click the cog icon -> Install plugin from disk
[jira-commit-message-3.4.0.zip](https://github.com/nemwiz/jira-commit-message-intellij-plugin/files/12326660/jira-commit-message-3.4.0.zip)

**Comment by REFUZIION** [comment]
Great! This works perfectly thanks a lot 🙏

**Comment by nemwiz** [comment]
You're welcome. I've just released the latest version, it should show up in IntelliJ in 1-2 days.
