### ISSUE TITLE
Prepend JIRA ID when message already exists, i.e. when message already created by Jetbrains AI Assistant, or typed in.

### ISSUE THREAD

**Issue by jimcornmell** [nemwiz/jira-commit-message-intellij-plugin#74]
Plugin needs a way to add the JIRA id to any existing text.

![jira-id](https://github.com/nemwiz/jira-commit-message-intellij-plugin/assets/7923416/f83d50e7-75d8-43f3-8142-d1596a8c5330)

**Comment by nemwiz** [comment]
Thanks for submitting this issue.

I still don't have access to AI assistant, but looking at this [blog post](https://blog.jetbrains.com/idea/2023/06/ai-assistant-in-jetbrains-ides/) in order to generate the commit message by AI, you need to trigger it first by clicking this icon with two purple stars.

Would you be so kind to confirm that this workflow is correct? So you would do something like this:
1. Click the purple stars and you get e.g. `message generated by AI`
2. Click the frog icon and your Jira issue gets prepended to the previous text e.g. `PROJ-123: message generated by AI`

It's possible to achieve this. There are folks who would like to keep the previous behavior, so I'm thinking that upon clicking the frog icon, you get a modal asking you if you want to prepend or only keep the Jira issue. If you have a better suggestion, happy to hear it.

**Comment by jimcornmell** [comment]
You are exactly right.

However I'd go for the fewest key presses, so maybe a setting to prepend, then in usage you just hit the AI button then the Frog!

**Comment by nemwiz** [comment]
Good suggestion. I've added a new checkbox in the settings to enable this. Could you test it out?

You can install this version by going to Plugins -> Click the cog icon -> Install plugin from disk
[jira-commit-message-3.4.0.zip](https://github.com/nemwiz/jira-commit-message-intellij-plugin/files/12326662/jira-commit-message-3.4.0.zip)

**Comment by jimcornmell** [comment]
Tested it worked fine.  Great work turning this around so fast!

**Comment by nemwiz** [comment]
I've just released the latest version, should be available in 1-2 days since it goes through some verification by JetBrains.
I saw that you also left a review for the plugin. I'm not sure if you can update it since we now support the functionality, but either way thanks for reporting this. :+1:
