### ISSUE TITLE
Last commit message should not always be cleared/reset on commit

### ISSUE THREAD

**Issue by brunpoern** [nemwiz/jira-commit-message-intellij-plugin#81]
Hi,

I really like the plugin especially the conventional commit support. It's very useful in my daily work but there is one little aspect which could be probably be improved:

Currently the last commit message is always reset if I commit the change in Intellij. Let's say I have a entered a commit message:

feat(ABC-42): my new feature

When I now press "Commit" or "Commit and Push..." the commit message is reset to:

feat(ABC-42): 

For me it would be more practicable if the last commit message would be kept, especially if I want to use the "Amend" feature where I now always have to enter the same message again (or replace it from history).

My suggestion would be that the plugin considers the "Clear initial commit message" option in Intellij (Settings - Version Control - Commit) to be consistent with the "default" behavior of IntelliJ:

- If "Clear initial commit message" is activated, the plugin should probably behave like today, i.e. reset the commit message to "feat(ABC-42): "
- If "Clear initial commit message" is not activated, the commit message should be kept after commit, i.e. in my example above it should still be "feat(ABC-42): my new feature" after pressing Commit.

Best regards,
Andreas

**Comment by nemwiz** [comment]
Hi Andreas,

Thank you for submitting this feature request. I understand what you are asking for but I also want to outline some ramifications of implementing this feature.

The plugin now works in some sort of **automatic** mode, you open the commit window, the message is populated. You change a branch, the commit message will be populated with new information etc. 
What you are asking is to turn this off and put the plugin in the let's call it **manual** mode. If you switch branches, your commit message would still show the message from the "previous" branch. You would have to click the frog icon and regenerate the message every time when you change branches, this is why I say **manual** mode.

Are you okay with this? I can definitely implement it.

You are also probably thinking - wait, for sure you can detect when I'm switching branches and you can populate the first message automatically for me? Yes, I can but I don't want to do this because the plugin then has some hidden behavior and assumes stuff. Maybe this would be okay for you, but for someone else this would be unexpected behavior and then I would get a bug request to turn this off. 😄 Or someone would ask for another options to control this behavior and I want to keep the plugin simple.

One of the problems of building an IntelliJ plugin is that I don't know how my plugin is used - maybe you are the only person out of 15000 that wants this feature. I hope you understand the tradeoffs now and if you are okay with a bit of clicking when you switch branches, I'd be happy to implement the feature you are asking. 👍 

Thanks

**Comment by brunpoern** [comment]
Hi and thanks for the quick response. I totally understand your arguments. Didn't consider this branch switching use case. In this case the behavior makes totally sense and I guess I would hate the manual mode here 😀

But what about the behavior if pressing Commit or Commit and Push? Wouldn't it make sense to consider here the IntelliJ configuration if commit message should be cleared or not.  So probably the following behavior would make sense:

- Open commit window or press commit -> only reset commit message if "Clear initial commit message" is enabled, otherwise keep the existing one
- Switch branch -> always reset commit message

So if "Clear initial commit message" is enabled, the behavior would be the same as now. And if not, the message would only be reset if branch is switched. But I have no glue about IntelliJ plugin development, i.e. I don't know if you can differentiate this UI interactions and how complicated it is to implement it. For instance what happens if commit window is not open while branch is switched. Then I would expect that message is reset if I open the commit window again. But if branch is not switched I would expect to see the old message

I mean, it's just a smaller issue for me and I will use the plugin anyhow 😀 So your plugin, your decision 😉

**Comment by nemwiz** [comment]
It's a bit more involved. 
I should probably add this to the documentation but the IntelliJ option under `Settings -> Version Control -> Commit -> Clear initial commit message` should always be off, otherwise you will never get a commit message from the plugin and will always have to click the icon manually.

The reason for this is that my plugin and that option listen for the same event. My plugin runs first, generates the message and then IntelliJ clears it and you get an empty commit message field. Relying on this option will not work and I also don't have access to it (e.g. the plugin can't know if you turned it on or off).

Sadly, the IntelliJ API and the ecosystem is limited and not easy to work with. The plugin doesn't know if you've pressed `Commit` or `Commit + Push`. The only thing I know is that the commit window opened, that's when the plugin runs and this is the only API exposed by the platform.

What you are asking for is a very specific behavior which would complicate the plugin. Because of all the reasons mentioned before, I would hold off from implementing this. If more people ask for this in the future, I'd be happy to reconsider.

In the meantime, what I can suggest is you compile your special version of the plugin. This code is open sourced and you can easily run it locally and build a dedicated version for yourself. You'll get a zip file which you can then install manually by `Preferences > Plugins -> ⚙️-> Install plugin from disk...`

On top of my head, you would need to make changes in a single file. [This is the function](https://github.com/nemwiz/jira-commit-message-intellij-plugin/blob/main/src/main/kotlin/org/nemwiz/jiracommitmessage/provider/PluginProvider.kt) that runs when the commit window is opened and probably a good place to write your logic,

Let me know in case you get stuck.

**Comment by brunpoern** [comment]
Hi Nemanja, thanks again for the detailed explanation and the hints plugin development. This is great support 👍 As written above, it's not so critical for me. I'm just starting to work with Git in IntelliJ and still need to make some experience what works best for me. And I anyhow can easily access the previous commit messages via commit message window history.

So from my side this feature request can be rejected. I understand now that my behavior is not so easy to implement  and I totally understand that you want to keep your plugin simple.

And if it bothers me too much, I will come back to you proposal and try to learn how to implement IntelliJ plugins 😀
